insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("dea49f3b4f","aston martin","db11","coupe","red",2022,2,"fuel","automatic",1500,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("b00c468155","cadillac","ct5","sedan","purple",2022,4,"fuel","manual",2400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("b5943745bd","bentley","bentayga","suv","white",2022,4,"fuel","automatic",2000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("f5817659c8","hyundai","bayon","suv","orange",2022,4,"fuel","manual",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("e0ed04e4a9","cadillac","ct6","sedan","black",2020,4,"fuel","automatic",2100,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("21907650de","bentley","bentayga","suv","blue",2022,4,"fuel","automatic",2000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("9550368d52","hyundai","accent","sedan","gold",2022,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("4fa0c827da","bmw","z4","coupe","white",2022,2,"fuel","automatic",940,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("693c3fa77f","chevrolet","cruze","sedan","beige",2022,4,"fuel","automatic",400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("5717aba7e6","jeep","wrangler","suv","blue",2022,4,"fuel","automatic",680,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("ea2c3a06e4","audi","a8","sedan","orange",2022,4,"fuel","automatic",800,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("499ad609ad","bugatti","chiron","sport","brown",2022,2,"fuel","automatic",3000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("7af05b2978","toyota","corolla","sedan","beige",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("14f787a0e6","jeep","wrangler","suv","silver",2022,4,"fuel","automatic",680,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("0bfc17e09f","hyundai","accent","sedan","silver",2022,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("db144c41d0","kia","carens","wagon","beige",2018,7,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("0859f27dcf","aston martin","db11","coupe","green",2022,2,"fuel","automatic",1500,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values(3385499e02,"bugatti","chiron","sport","black",2022,2,"fuel","automatic",3000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("1fb259e1ba","toyota","corolla","sedan","purple",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("772fbc3f50","bentley","bentayga","suv","black",2022,4,"fuel","automatic",2000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("4fa9091b48","chevrolet","cruze","sedan","gold",2022,4,"fuel","automatic",400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("3906fce057","bmw","i7","sedan","silver",2023,4,"fuel","automatic",1950,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("6730e0fb44","hyundai","accent","sedan","silver",2022,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("afb22c0c03","chevrolet","cruze","sedan","green",2022,4,"fuel","automatic",400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values(7063239473,"chevrolet","cruze","sedan","gray",2022,4,"fuel","automatic",400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("3993ab941d","cadillac","ct5","sedan","silver",2022,4,"fuel","manual",2400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("f119da3d5a","toyota","corolla","sedan","purple",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("55700a505d","bmw","x7","suv","blue",2022,4,"fuel","automatic",1830,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("55bcf9533a","jeep","wrangler","suv","gold",2022,4,"fuel","automatic",680,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("b45bc2d37d","bentley","bentayga","suv","beige",2022,4,"fuel","automatic",2000,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("a0c04bb989","aston martin","db11","coupe","beige",2022,2,"fuel","automatic",1500,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("1671b27a9d","aston martin","db11","coupe","orange",2022,2,"fuel","automatic",1500,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("1b8a1de6c4","mercedes","e-class","sedan","purple",2022,4,"fuel","automatic",1850,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values(3687847168,"cadillac","ct5","sedan","blue",2022,4,"fuel","manual",2400,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("7ddb8cac30","toyota","corolla","sedan","gold",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("dcd7418095","toyota","corolla","sedan","beige",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("feebe3ebd4","bmw","x1","suv","silver",2022,4,"fuel","automatic",550,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("714f369377","hyundai","accent","sedan","brown",2022,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("dcbf7cbc7c","toyota","corolla","sedan","yellow",2016,4,"fuel","automatic",350,"active")
insert into car(id,brand,model,type,color,year,seating,powertrain,transmission,rate,status) values("6decd588ee","bmw","x7","suv","brown",2022,4,"fuel","automatic",1830,"active")